package Library_Managment_System.StudentBooks.DTOs;

public class AuthorRequestDTO {


    //this is just an object that'll be used to take request from postman

    //will only have certain params, that are needed as user input

    //id is not here -> autogenerated, user cant enter random values
    private String name;
    private int age;
    private String country;

    //constructor
    public AuthorRequestDTO() {

    }

    public AuthorRequestDTO(String name, int age, String country) {
        this.name = name;
        this.age = age;
        this.country = country;
    }

    //getters and setters
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public int getAge() { return age; }
    public void setAge(int age) { this.age = age; }

    public String getCountry() { return country; }
    public void setCountry(String country) { this.country = country; }

}
